#!/usr/bin/env bash
#display contents of file that re username, userid, home directory path for user

while IFS=':' read -r login _ uid _ _ home _
do
    printf '%s:%s:%s\n' "${login}" "${uid}" "${home}"
done </etc/passwd
