#!/usr/bin/env bash
# Displaying Best School 10 times but for the 9th iteration display Best school + the Hi on a new line using the while loop.
i=0
while [ $i -lt 10 ]; do
	echo Best School
	((i++))
	if [ $i -eq 9 ]; then
	   echo Hi
	fi
done
