#!/usr/bin/env bash
# this script display To infinity and beyond with a sleep 2 iteration.
# Display I am invincible !!! when receiving SIGTERM signal

trap 'echo "I am invincible!!!"' 15
while true; do
    echo "to infinity and beyond"
    sleep 2
done
